### ISSUE TITLE
vidéo homepage 

### ISSUE THREAD

**Issue by NanaB38** [ComicScrip/lyon-react-mars22-p2g3#39]
# Le besoin

En tant qu'utilisateur, je souhaite voir une page d'accueil dynamique avec une vidéo en fond qui compile plusieurs extraits vidéos : mini-teasers de films.

## Critères et considérations spécifiques

- [ ] Conformité à l'écran "Landingpage" sur la maquette mobile 
- [ ] Conformité à l'écran "Landingpage" sur la maquette desktop

#### Actions à réaliser

- se rendre sur la page "home" accessible depuis l'URL `/` ou en cliquant sur le logo "cinéchill" de la navbar

#### Verifications

- [ ] On voit bien les mini-teasers de plusieurs films défiler en background 
- [ ] Ils sont lus en boucle 

## A faire

- [ ] créer une vidéo avec plusieurs mini-extraits 
- [ ] lire la vidéo en boucle

**Comment by ComicScrip** [comment]
validé
